### PR TITLE
Moved boto3 to extras_require to accommodate AWS Lamda

### PR DESCRIPTION
**Pull request by joseph-wortmann**
#3

### CODE REVIEW

**Comment by peterdemin** [comment]
Ah, I had another solution in mind. Sorry for not being clear.
It will be easier to just filter out boto3 in [setup.py](https://github.com/peterdemin/awsme/blob/master/setup.py#L19) and leave all the requirements files as is.

**Comment by joseph-wortmann** [comment]
Ahh! I can do that.

**Comment by joseph-wortmann** [comment]
Build worked anyhow, but I'm adding back in and filtering as you suggest.

**Comment by joseph-wortmann** [comment]
Ok - added back in and filtered. I also removed the `\n` in the list.

**Comment by peterdemin** [comment]
Cool! I'll try to cut a release tonight.

**Pull request merged**
